apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"1"},"creationTimestamp":"2023-11-24T21:56:53Z","generation":1,"labels":{"app":"my-deployment"},"name":"my-deployment","namespace":"default","resourceVersion":"6415","uid":"c79047f6-7172-47b2-8999-ea478bf48c58"},"spec":{"progressDeadlineSeconds":600,"replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"my-deployment"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"my-deployment"}},"spec":{"containers":[{"image":"us-central1-docker.pkg.dev/ds-561-vanisinghal/quickstart-docker-repo/quickstart-image:tag1","imagePullPolicy":"IfNotPresent","name":"quickstart-image","resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"serviceAccountName":"gke-service-account","terminationGracePeriodSeconds":30}}},"status":{"availableReplicas":1,"conditions":[{"lastTransitionTime":"2023-11-24T21:57:01Z","lastUpdateTime":"2023-11-24T21:57:01Z","message":"Deployment has minimum availability.","reason":"MinimumReplicasAvailable","status":"True","type":"Available"},{"lastTransitionTime":"2023-11-24T21:56:53Z","lastUpdateTime":"2023-11-24T21:57:01Z","message":"ReplicaSet \"my-deployment-69ddbc846\" has successfully progressed.","reason":"NewReplicaSetAvailable","status":"True","type":"Progressing"}],"observedGeneration":1,"readyReplicas":1,"replicas":1,"updatedReplicas":1}}
  creationTimestamp: "2023-11-24T21:56:53Z"
  generation: 2
  labels:
    app: my-deployment
  name: my-deployment
  namespace: default
  resourceVersion: "548447"
  uid: c79047f6-7172-47b2-8999-ea478bf48c58
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: my-deployment
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: my-deployment
    spec:
      containers:
      - image: us-central1-docker.pkg.dev/ds-561-vanisinghal/quickstart-docker-repo/quickstart-image:tag1
        imagePullPolicy: IfNotPresent
        name: quickstart-image
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: gke-service-account
      serviceAccountName: gke-service-account
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2023-11-24T21:56:53Z"
    lastUpdateTime: "2023-11-25T17:43:26Z"
    message: ReplicaSet "my-deployment-597bb6d9db" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2023-11-25T17:57:03Z"
    lastUpdateTime: "2023-11-25T17:57:03Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
